#!/bin/bash
set -e;

# Check if name is specified
if [[ $1 == mysql:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

if [[ ! -d $DOKKU_ROOT/.mysql ]]; then
    mkdir -p $DOKKU_ROOT/.mysql
    chown -R dokku: $DOKKU_ROOT/.mysql
fi

case "$1" in

  mysql:create)
    DB_IMAGE=mysql/$APP
    # Check if DB container is installed
    IMAGE=$(docker images | grep "hughfletcher/mysql " |  awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "MySql image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi
    # Check if an existing DB volume exists
    if [[ -f "$DOKKU_ROO/.mysql/volume_$APP" ]]; then
        VOLUME="`cat $DOKKU_ROOT/.mysql/volume_$APP`:/opt/mysql"
        echo
        echo "-----> Reusing mysql/$APP database"
    else
        VOLUME="/opt/mysql"
        # Generate a random password for DB user
        DB_PASS=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
        # DB_NAME=$(echo "www.atomic24.com" | sed -e 's/\.//g')
        # DB_USER='user'$RANDOM
        # Temporarily store it to a file
        echo $DB_PASS > "$DOKKU_ROOT/.mysql/pwd_$APP"
        chown dokku: "$DOKKU_ROOT/.mysql/pwd_$APP"
        chmod 700 "$DOKKU_ROOT/.mysql/pwd_$APP"
    fi
    # Fork DB image
    ID=$(docker run -d hughfletcher/mysql exit 0)
    if [[ -z "$ID" ]]; then
        docker stop $ID > /dev/null
    fi
    docker wait $ID > /dev/null
    IMAGE=$(docker commit $ID)
    docker tag $IMAGE $DB_IMAGE
    # Launch container
    ID=$(docker run -v $VOLUME -p 3306 -d $DB_IMAGE /usr/sbin/mysqld)
    sleep 4

    if [[ ! -f "$DOKKU_ROOT/.mysql/volume_$APP" ]]; then
        VOLUME_PATH=$(docker inspect $ID | grep /var/lib/docker/vfs/dir/ | awk '{print $2}' | sed -e's/"//g')
        IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
        docker run $DB_IMAGE mysqladmin -h $IP -u admin -p'mysql-server' password $DB_PASS
        docker run $DB_IMAGE mysqladmin -h $IP -u admin -p$DB_PASS create 'db'
        # docker run mysql/create mysql -h $IP -u admin -p'newpass' -e "RENAME USER admin@'%' TO $DB_USER@'%';"

        # Rename persistent volume
        if [[ -z $VOLUME_PATH ]]; then
            echo "Your docker version is too old, please update it"
            exit 1
        fi
        echo $VOLUME_PATH > "$DOKKU_ROOT/.mysql/volume_$APP"
    fi
    PORT=$(docker port $ID 3306 | sed 's/0.0.0.0://')
    echo $PORT > "$DOKKU_ROOT/.mysql/port_$APP"
    # Link to a potential existing app
    dokku mysql:link $APP $APP
    echo
    echo "-----> MySql container created: $DB_IMAGE"
    sleep 1
    dokku mysql:info $APP
    ;;

  mysql:delete)
    DB_IMAGE=mysql/$APP
    # Stop and remove the container
    ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
    if [[ ! -z $ID ]]; then
        docker kill $ID > /dev/null
        sleep 1
        docker rm -v $ID > /dev/null
        sleep 1
    fi
    # Remove image
    IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
    if [[ ! -z $IMAGE ]]; then
        docker rmi $IMAGE
    fi
    # Remove container port storage
    if [[ -f "$DOKKU_ROOT/.mysql/port_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.mysql/port_$APP"
    fi
    # Remove container root password
    if [[ -f "$DOKKU_ROOT/.mysql/pwd_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.mysql/pwd_$APP"
    fi
    # Remove persistent volume
    if [[ -f "$DOKKU_ROOT/.mysql/volume_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.mysql/volume_$APP"
    fi
    echo
    echo "-----> MySql container deleted: $DB_IMAGE"
    ;;

  mysql:info)
    DB_IMAGE=mysql/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
    echo "$ID"
    # PORT=$(docker port $ID 5432)
    echo
    echo "       Host: $IP"
    echo "       User: 'admin'"
    if [[ -f "$DOKKU_ROOT/.mysql/pwd_$APP" ]]; then
        echo "       Password: '$(cat "$DOKKU_ROOT/.mysql/pwd_$APP")'"
    fi
    echo "       Database: 'db'"
    # echo "       Public port: $PORT"
    echo "       Internal port: 3306"
    echo
    ;;

  mysql:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a database name"
            exit 1
        fi
        DB_IMAGE="mysql/$3"
        # Check temporarily file
        if [[ ! -f "$DOKKU_ROOT/.mysql/pwd_$3" ]]; then
            echo "Database is not initialized correctly"
            exit 1
        fi
        DB_PASSWORD=$(cat "$DOKKU_ROOT/.mysql/pwd_$APP")
        ID=$(docker ps | grep "$DB_IMAGE":latest |  awk '{print $1}')
        IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
        # Write database connection vars to app's ENV file
        # I know there has to be a more eloquent method of doing this...
        HOST="DB_HOST=$IP"
        USER="DB_USER=admin"
        PASS="DB_PASS=$DB_PASSWORD"
        NAME="DB_NAME=db"
        PORT="DB_PORT=3306"
        dokku config:set $APP $HOST $USER $PASS $NAME $PORT
        echo
        echo "-----> $APP linked to $DB_IMAGE database"
    fi
    ;;

  mysql:logs)
    DB_IMAGE=mysql/$APP
    ID=$(docker ps -a | grep "$DB_IMAGE" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  mysql-tests)
        echo ">>> Running Tests"
        /usr/bin/shunit2 /var/lib/dokku/plugins/mysql/tests/commands
    ;;

  help)
    cat && cat<<EOF
    mysql:create <app>     Create a MySql container
    mysql:delete <app>     Delete specified MySql container
    mysql:info <app>       Display database informations
    mysql:link <app> <db>  Link an app to a MySql database
    mysql:logs <app>       Display last logs from MySql container
EOF
    ;;

esac
